-- Supabase migration: Create tables for SignalForge
-- Run this in Supabase SQL editor or via Supabase CLI

-- Enable RLS
alter schema public owner to postgres;

-- Create signals table
create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  token text not null,
  action text not null default 'HOLD',
  price numeric(18, 10) not null default 0,
  volume_24h bigint default 0,
  liquidity bigint default 0,
  holders integer default 0,
  confidence numeric(3, 2) default 0,
  og_analysis jsonb,
  created_at timestamptz default now()
);

-- Create executions table
create table if not exists public.executions (
  id bigint generated by default as identity primary key,
  signal_id bigint references public.signals(id) on delete cascade,
  status text not null default 'pending',
  tx_hash text,
  executed_at timestamptz,
  error_message text,
  created_at timestamptz default now()
);

-- Create agent_decisions table
create table if not exists public.agent_decisions (
  id bigint generated by default as identity primary key,
  signal_id bigint references public.signals(id) on delete cascade,
  agent text not null default '0g-lite',
  decision text not null,
  confidence numeric(3, 2) default 0,
  reasoning text,
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.signals enable row level security;
alter table public.executions enable row level security;
alter table public.agent_decisions enable row level security;

-- Create policies (allow all for service role)
create policy "Allow service role full access on signals"
  on public.signals for all
  to service_role
  using (true)
  with check (true);

create policy "Allow service role full access on executions"
  on public.executions for all
  to service_role
  using (true)
  with check (true);

create policy "Allow service role full access on agent_decisions"
  on public.agent_decisions for all
  to service_role
  using (true)
  with check (true);

-- Create indexes
create index if not exists idx_signals_token on public.signals(token);
create index if not exists idx_signals_created_at on public.signals(created_at desc);
create index if not exists idx_executions_signal_id on public.executions(signal_id);
create index if not exists idx_agent_decisions_signal_id on public.agent_decisions(signal_id);
